proto_dashboard:
    path: /dashboard
    defaults:
        _controller: ezsystems.platformui.controller.proto:dashboardAction
# by default toolbars are hidden, so the following is not really needed
#        toolbars:
#            discovery: 0
    methods: [GET]

proto_viewLocation:
    # could/should we reuse the Location's nice URL, so that to browse we could
    # have /proto/My-Nice-URL/To/A/Location ?
    path: /location/view/{locationId}
    defaults:
        _controller: ezsystems.platformui.controller.proto:locationViewAction
        toolbars:
            discovery: 1
    methods: [GET]
    requirements:
        locationId: \d+
    options:
        expose: true
