proto_dashboard:
    path: /dashboard
    defaults:
        _controller: ezsystems.platformui.controller.proto:dashboardAction
        appConfig:
            mainContent:
                template: 'eZPlatformUIBundle:PlatformUI:dashboard.html.twig'
                parameters: []
            toolbars:
            # by default toolbars are hidden, so the following is not really needed
            #     discovery: 0
    methods: [GET]

proto_viewLocation:
    # could/should we reuse the Location's nice URL, so that to browse we could
    # have /proto/My-Nice-URL/To/A/Location ?
    path: /location/view/{locationId}
    defaults:
        _controller: ezsystems.platformui.controller.proto:locationViewAction
        appConfig:
            toolbars:
                discovery: 1
            mainContent:
                template: 'eZPlatformUIBundle:PlatformUI:locationview.html.twig'
                parameters: []
    methods: [GET]
    requirements:
        locationId: \d+
    options:
        expose: true
