
shell:
    pattern: /shell
    defaults: { _controller: eZPlatformUIBundle:PlatformUI:shell }

admin_dashboard:
    pattern: /pjax/dashboard
    defaults:
        _controller: ezsystems.platformui.controller.dashboard:dashboardAction
    methods: [GET]

admin_systeminfo:
    pattern: /pjax/systeminfo
    defaults:
        _controller: ezsystems.platformui.controller.systeminfo:infoAction
    methods: [GET]

admin_phpinfo:
    pattern: /systeminfo/phpinfo
    defaults:
        _controller: ezsystems.platformui.controller.systeminfo:phpinfoAction
    methods: [GET]
