parameters:
    ezsystems.platformui.twig.yui_extension.class: EzSystems\PlatformUIBundle\Twig\TwigYuiExtension
    ezsystems.platformui.controller.dashboard.class: EzSystems\PlatformUIBundle\Controller\DashboardController

services:
    ezsystems.platformui.twig.yui_extension:
        class: %ezsystems.platformui.twig.yui_extension.class%
        arguments: [%yui%]
        tags:
            - { name: twig.extension }

    ezsystems.platformui.controller.dashboard:
        class: %ezsystems.platformui.controller.dashboard.class%
        parent: ezpublish.controller.base
