parameters:
    # use the EzSystemsEditorialBundle's pagelayout
    # Remove this as soon as we have a proper design/theme system
    ezpublish_legacy.ezdemo_site_user.view_default_layout: eZEditorialBundle::pagelayout.html.twig
    ezpublish_legacy.eng.view_default_layout: eZEditorialBundle::pagelayout.html.twig

    ezsystems.editorial.twig.yui_extension.class: EzSystems\EditorialBundle\Twig\TwigYuiExtension

services:
    ezsystems.editorial.twig.yui_extension:
        class: %ezsystems.editorial.twig.yui_extension.class%
        arguments: [%yui%]
        tags:
            - { name: twig.extension }
