parameters:
    # use the EzSystemsEditorialBundle's pagelayout
    # Remove this as soon as we have a proper design/theme system
    ezpublish_legacy.ezdemo_site_user.view_default_layout: EzSystemsEditorialBundle::pagelayout.html.twig
    ezpublish_legacy.eng.view_default_layout: EzSystemsEditorialBundle::pagelayout.html.twig

services:
#    ez_systems_editorial.example:
#        class: %ez_systems_editorial.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
