parameters:
    ezsystems.platformui.twig.yui_extension.class: EzSystems\PlatformUIBundle\Twig\TwigYuiExtension
    ezsystems.platformui.test.twig.yui_extension.class: EzSystems\PlatformUIBundle\Test\Twig\TwigYuiExtensionTest

services:
    ezsystems.platformui.twig.yui_extension:
        class: %ezsystems.platformui.twig.yui_extension.class%
        arguments: [%yui%]
        tags:
            - { name: twig.extension }
