system:
    default:
        yui:
            filter: min
            modules:
                ez-capi:
                    path: %ez_platformui.public_dir%/vendors/ez-js-rest-client/dist/CAPI.js
                ez-platformuiapp:
                    requires:
                        - 'app'
                        - 'app-transitions'
                        - 'node-screen'
                        - 'parallel'
                        - 'ez-capi'
                        - 'ez-loginformviewservice'
                        - 'ez-loginformview'
                        - 'ez-dashboardview'
                        - 'ez-contenteditviewservice'
                        - 'ez-contenteditview'
                        - 'ez-locationviewview'
                        - 'ez-locationviewviewservice'
                        - 'ez-navigationhubviewservice'
                        - 'ez-navigationhubview'
                        - 'ez-discoverybarviewservice'
                        - 'ez-discoverybarview'
                        - 'ez-errorview'
                        - 'ez-usermodel'
                        - 'ez-pluginregistry'
                        - 'ez-registerpartialsplugin'
                        - 'ez-registerurlhelpersplugin'
                        - 'ez-domstateplugin'
                    path: %ez_platformui.public_dir%/js/apps/ez-platformuiapp.js
                ez-viewservice:
                    requires: ['base', 'parallel']
                    path: %ez_platformui.public_dir%/js/views/services/ez-viewservice.js
                ez-loginformviewservice:
                    requires: ['ez-viewservice']
                    path: %ez_platformui.public_dir%/js/views/services/ez-loginformviewservice.js
                ez-contenteditviewservice:
                    requires: ['parallel', 'ez-viewservice', 'ez-contentmodel', 'ez-locationmodel', 'ez-contenttypemodel', 'ez-usermodel', 'ez-versionmodel']
                    path: %ez_platformui.public_dir%/js/views/services/ez-contenteditviewservice.js
                ez-locationviewviewservice:
                    requires: ['parallel', 'ez-viewservice', 'ez-locationmodel', 'ez-contentmodel', 'ez-objectrelationloadplugin']
                    path: %ez_platformui.public_dir%/js/views/services/ez-locationviewviewservice.js
                ez-navigationhubviewservice:
                    requires: ['ez-viewservice']
                    path: %ez_platformui.public_dir%/js/views/services/ez-navigationhubviewservice.js
                ez-discoverybarviewservice:
                    requires: ['ez-viewservice', 'ez-contenttreeplugin']
                    path: %ez_platformui.public_dir%/js/views/services/ez-discoverybarviewservice.js
                ez-serversideviewservice:
                    requires: ['io-base', 'ez-viewservice']
                    path: %ez_platformui.public_dir%/js/views/services/ez-serversideviewservice.js
                ez-view:
                    requires: ['view', 'base-pluginhost', 'ez-pluginregistry']
                    path: %ez_platformui.public_dir%/js/views/ez-view.js
                ez-templatebasedview:
                    requires: ['ez-texthelper', 'ez-view', 'handlebars', 'template']
                    path: %ez_platformui.public_dir%/js/views/ez-templatebasedview.js
                ez-loginformview:
                    requires: ['ez-templatebasedview', 'node-style']
                    path: %ez_platformui.public_dir%/js/views/ez-loginformview.js
                ez-dashboardview:
                    requires: ['ez-templatebasedview']
                    path: %ez_platformui.public_dir%/js/views/ez-dashboardview.js
                ez-locationviewview:
                    requires: ['ez-templatebasedview', 'ez-actionbarview', 'ez-rawcontentview', 'ez-tabs', 'event-tap', 'array-extras']
                    path: %ez_platformui.public_dir%/js/views/ez-locationviewview.js
                ez-navigationhubview:
                    requires: ['ez-templatebasedview', 'event-tap', 'node-screen', 'node-style', 'event-outside']
                    path: %ez_platformui.public_dir%/js/views/ez-navigationhubview.js
                ez-discoverybarview:
                    requires: ['ez-barview', 'ez-buttonactionview', 'ez-treeactionview']
                    path: %ez_platformui.public_dir%/js/views/ez-discoverybarview.js
                ez-actionbarview:
                    requires: ['ez-barview', 'ez-buttonactionview']
                    path: %ez_platformui.public_dir%/js/views/ez-actionbarview.js
                ez-rawcontentview:
                    requires:
                        - 'ez-templatebasedview'
                        - 'ez-accordion-element'
                        - 'ez-fieldview'
                        - 'ez-contentmodel'
                        - 'ez-contenttypemodel'
                        - 'ez-checkbox-view'
                        - 'ez-relation-view'
                        - 'ez-url-view'
                        - 'ez-selection-view'
                        - 'ez-user-view'
                        - 'ez-maplocation-view'
                        - 'ez-author-view'
                        - 'event-tap'
                    path: %ez_platformui.public_dir%/js/views/ez-rawcontentview.js
                ez-contenteditview:
                    requires: ['ez-templatebasedview', 'ez-contenteditformview', 'ez-editactionbarview', 'event-tap']
                    path: %ez_platformui.public_dir%/js/views/ez-contenteditview.js
                ez-contenteditformview:
                    requires:
                        - 'ez-templatebasedview'
                        - 'ez-accordion-element'
                        - 'ez-checkbox-editview'
                        - 'ez-textline-editview'
                        - 'ez-textblock-editview'
                        - 'ez-emailaddress-editview'
                        - 'ez-maplocation-editview'
                        - 'ez-url-editview'
                        - 'ez-author-editview'
                        - 'ez-float-editview'
                        - 'ez-integer-editview'
                        - 'ez-selection-editview'
                        - 'event-tap'
                    path: %ez_platformui.public_dir%/js/views/ez-contenteditformview.js
                ez-errorview:
                    requires: ['ez-templatebasedview', 'event-tap']
                    path: %ez_platformui.public_dir%/js/views/ez-errorview.js
                ez-fieldeditview:
                    requires: ['ez-templatebasedview', 'event-tap', 'event-outside', 'node-style']
                    path: %ez_platformui.public_dir%/js/views/ez-fieldeditview.js
                ez-fieldview:
                    requires: ['ez-templatebasedview']
                    path: %ez_platformui.public_dir%/js/views/ez-fieldview.js
                ez-checkbox-view:
                    requires: ['ez-fieldview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-checkbox-view.js
                ez-checkbox-editview:
                    requires: ['ez-fieldeditview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-checkbox-editview.js
                ez-textline-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-textline-editview.js
                ez-textblock-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-textblock-editview.js
                ez-emailaddress-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-emailaddress-editview.js
                ez-relation-view:
                    requires: ['ez-fieldview', 'event-tap']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-relation-view.js
                ez-user-view:
                    requires: ['ez-fieldview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-user-view.js
                ez-selection-view:
                    requires: ['ez-fieldview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-selection-view.js
                ez-url-view:
                    requires: ['ez-fieldview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-url-view.js
                ez-url-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-url-editview.js
                ez-author-view:
                    requires: ['ez-fieldview']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-author-view.js
                ez-author-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange', 'event-tap', 'model', 'model-list']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-author-editview.js
                ez-float-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-float-editview.js
                ez-integer-editview:
                    requires: ['ez-fieldeditview', 'event-valuechange']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-integer-editview.js
                ez-maplocation-view:
                    requires: ['ez-fieldview', 'ez-googlemapapiloader']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-maplocation-view.js
                ez-maplocation-editview:
                    requires: ['ez-fieldeditview', 'ez-googlemapapiloader']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-maplocation-editview.js
                ez-selection-editview:
                    requires: ['ez-fieldeditview', 'ez-selectionfilterview', 'event-tap', 'event-outside', 'node-screen']
                    path: %ez_platformui.public_dir%/js/views/fields/ez-selection-editview.js
                ez-selectionfilterview:
                    requires: ['autocomplete-base', 'autocomplete-highlighters', 'autocomplete-filters', 'event-tap', 'view']
                    path: %ez_platformui.public_dir%/js/views/ez-selectionfilterview.js
                ez-restmodel:
                    requires: ['model', 'json']
                    path: %ez_platformui.public_dir%/js/models/ez-restmodel.js
                ez-contentmodel:
                    requires: ['ez-restmodel', 'array-extras']
                    path: %ez_platformui.public_dir%/js/models/ez-contentmodel.js
                ez-versionmodel:
                    requires: ['ez-restmodel']
                    path: %ez_platformui.public_dir%/js/models/ez-versionmodel.js
                ez-locationmodel:
                    requires: ['ez-restmodel']
                    path: %ez_platformui.public_dir%/js/models/ez-locationmodel.js
                ez-usermodel:
                    requires: ['ez-restmodel']
                    path: %ez_platformui.public_dir%/js/models/ez-usermodel.js
                ez-contenttypemodel:
                    requires: ['ez-restmodel']
                    path: %ez_platformui.public_dir%/js/models/ez-contenttypemodel.js
                ez-contenttree:
                    requires: ['tree', 'tree-openable', 'tree-selectable', 'tree-lazy']
                    path: %ez_platformui.public_dir%/js/models/structs/ez-contenttree.js
                ez-editactionbarview:
                    requires: ['ez-barview', 'ez-buttonactionview', 'ez-previewactionview']
                    path: %ez_platformui.public_dir%/js/views/ez-editactionbarview.js
                ez-buttonactionview:
                    requires: ['ez-templatebasedview']
                    path: %ez_platformui.public_dir%/js/views/actions/ez-buttonactionview.js
                ez-previewactionview:
                    requires: ['ez-buttonactionview', 'ez-editpreviewview']
                    path: %ez_platformui.public_dir%/js/views/actions/ez-previewactionview.js
                ez-treeactionview:
                    requires: ['ez-buttonactionview', 'ez-expandable', 'event-tap', 'event-outside', 'handlebars', 'node-style']
                    path: %ez_platformui.public_dir%/js/views/actions/ez-treeactionview.js
                ez-editpreviewview:
                    requires: ['ez-templatebasedview', 'event-tap']
                    path: %ez_platformui.public_dir%/js/views/ez-editpreviewview.js
                ez-barview:
                    requires: ['ez-templatebasedview', 'event-tap', 'event-resize']
                    path: %ez_platformui.public_dir%/js/views/ez-barview.js
                ez-serversideview:
                    requires: ['ez-view', 'ez-tabs', 'ez-selection-table', 'event-tap']
                    path: %ez_platformui.public_dir%/js/views/ez-serversideview.js
                ez-texthelper:
                    requires: ['handlebars']
                    path: %ez_platformui.public_dir%/js/helpers/ez-texthelper.js
                ez-googlemapapiloader:
                    requires: ['jsonp', 'jsonp-url', 'event-custom']
                    path: %ez_platformui.public_dir%/js/services/ez-googlemapapiloader.js
                ez-pluginregistry:
                    requires: ['array-extras']
                    path: %ez_platformui.public_dir%/js/services/ez-pluginregistry.js
                ez-domstateplugin:
                    requires: ['plugin', 'base', 'node', 'ez-pluginregistry']
                    path: %ez_platformui.public_dir%/js/apps/plugins/ez-domstateplugin.js
                ez-registerpartialsplugin:
                    requires: ['plugin', 'handlebars', 'base', 'node', 'ez-pluginregistry']
                    path: %ez_platformui.public_dir%/js/apps/plugins/ez-registerpartialsplugin.js
                ez-registerurlhelpersplugin:
                    requires: ['plugin', 'handlebars', 'base', 'ez-pluginregistry']
                    path: %ez_platformui.public_dir%/js/apps/plugins/ez-registerurlhelpersplugin.js
                ez-viewservicebaseplugin:
                    requires: ['plugin', 'base']
                    path: %ez_platformui.public_dir%/js/views/services/plugins/ez-viewservicebaseplugin.js
                ez-objectrelationloadplugin:
                    requires: ['ez-viewservicebaseplugin', 'ez-pluginregistry', 'ez-contentmodel']
                    path: %ez_platformui.public_dir%/js/views/services/plugins/ez-objectrelationloadplugin.js
                ez-contenttreeplugin:
                    requires: ['ez-viewservicebaseplugin', 'ez-pluginregistry', 'ez-contentmodel', 'ez-contenttypemodel', 'ez-locationmodel', 'ez-contenttree']
                    path: %ez_platformui.public_dir%/js/views/services/plugins/ez-contenttreeplugin.js
                ez-expandable:
                    requires: ['view']
                    path: %ez_platformui.public_dir%/js/extensions/ez-expandable.js
                ez-accordion-element:
                    requires: ['transition']
                    path: %ez_platformui.public_dir%/js/extensions/ez-accordion-element.js
                ez-tabs:
                    requires: ['node']
                    path: %ez_platformui.public_dir%/js/extensions/ez-tabs.js
                ez-selection-table:
                    requires: ['node']
                    path: %ez_platformui.public_dir%/js/extensions/ez-selection-table.js
                ez-app-extension:
                    requires: ['base']
                    path: %ez_platformui.public_dir%/js/apps/extensions/ez-app-extension.js
                ez-app-extension-admin:
                    requires: ['ez-serversideview', 'ez-serversideviewservice', 'ez-app-extension']
                    path: %ez_platformui.public_dir%/js/apps/extensions/ez-app-extension-admin.js
