sudo: false
language: php
php:
    - "5.5"
    - "5.6"
    - "7.0"
env:
    matrix:
        - CODE="php"
          BEFORE="composer install --prefer-dist"
          TEST_CMD="./vendor/phpunit/phpunit/phpunit -c phpunit.xml"
          AFTER_SUCCESS="echo \"After success\""
        - CODE="js"
          BEFORE="./bin/travis/runjstests.sh ./bin/travis/setupnode.sh"
          TEST_CMD="./bin/travis/runjstests.sh \"grunt test\""
          AFTER_SUCCESS="./bin/travis/runjstests.sh ./bin/travis/generate_apidoc.sh"
    global:
        secure: "aNPcXEtgV3Q/GVCH+FvITm/gLXcNyFl7YiOT9JcqZUwYXsT2zi8g4BcwBgDtpbSmi8NSCsEWONNxxDM10BqCPzfkiFD2I0cPHXVxmJ3cmOqySci5JvysEd+RU6gnatCxqzAJYDH2BanfPyu+yPwrSIgWdkPuvNhydNJFUrwsinw="

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - $BEFORE

script: $TEST_CMD

after_success:
    - if [ $TRAVIS_PULL_REQUEST = "false" ] ; then $AFTER_SUCCESS ; fi
