language: php
php:
    - "5.6"
sudo: false
env:
    matrix:
        - CODE="php"
          BEFORE_GLOBAL="echo \"Before global\""
          BEFORE_LOCAL="composer install --prefer-dist"
          TEST_CMD="./vendor/phpunit/phpunit/phpunit -c phpunit.xml"
          AFTER_SUCCESS="echo \"After success\""
        - CODE="js"
          BEFORE_GLOBAL="./bin/travis/setupnode.sh"
          BEFORE_LOCAL="./bin/travis/localjsdeps.sh"
          TEST_CMD="grunt test"
          AFTER_SUCCESS="sh bin/travis/generate_apidoc.sh"
    global:
        secure: "aNPcXEtgV3Q/GVCH+FvITm/gLXcNyFl7YiOT9JcqZUwYXsT2zi8g4BcwBgDtpbSmi8NSCsEWONNxxDM10BqCPzfkiFD2I0cPHXVxmJ3cmOqySci5JvysEd+RU6gnatCxqzAJYDH2BanfPyu+yPwrSIgWdkPuvNhydNJFUrwsinw="

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - $BEFORE_GLOBAL
    - $BEFORE_LOCAL

script: $TEST_CMD

after_success:
    - if [ $TRAVIS_PULL_REQUEST = "false" ] ; then $AFTER_SUCCESS ; fi
